name: Tests

on:
  push:
  pull_request:

jobs:
  php5:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['5.6']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: mongodb, redis
          coverage: xdebug

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit --coverage-text --testsuite="Mockery Test Suite PHP5"

  php7:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: mongodb, redis
          coverage: xdebug

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit --coverage-text --testsuite="Mockery Test Suite PHP7"

  php80:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['8.0']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit --coverage-text --testsuite="Mockery Test Suite PHP8"

  php81:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['8.1']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Mimic PHP 8.0
        run: composer config platform.php 8.0.999

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit --testsuite="Mockery Test Suite PHP8"
